blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/golang/vscode-go/issues/new?template=feature_request.md
    about: Please file a feature request here....
